"""
Review and validate AI-generated questions.

This script helps you:
- Review unvalidated questions
- Mark them as validated
- Edit questions that need fixes
- Delete poor quality questions

Usage:
    python scripts/validate_generated_questions.py
"""

import sys
import os

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../src')))

from repositories.question_repository import QuestionRepository
from models.question import Question


def list_unvalidated_questions(repo: QuestionRepository):
    """List all questions that need validation."""
    all_questions = repo.list_all()
    unvalidated = [q for q in all_questions if not q.validated]

    if not unvalidated:
        print("✅ All questions are validated!")
        return []

    print(f"\n📋 Found {len(unvalidated)} unvalidated questions:\n")

    for i, q in enumerate(unvalidated, 1):
        print(f"{i}. [{q.category}] {q.question_text}")
        print(f"   Topic: {q.topic_id} | Source: {q.source_reference.document} (p.{q.source_reference.page})")
        print(f"   Generated by: {q.generated_by} | ID: {q.question_id}")
        print()

    return unvalidated


def review_question(question: Question):
    """Display a question for review."""
    print("\n" + "=" * 70)
    print("QUESTION REVIEW")
    print("=" * 70)
    print(f"\nCategory: {question.category}")
    print(f"Topic: {question.topic_id}")
    print(f"Difficulty: {question.difficulty}")
    print(f"\nQuestion: {question.question_text}\n")

    for opt in question.answer_options:
        marker = "✓ CORRECT" if opt.id == question.correct_answer else ""
        print(f"  {opt.id}. {opt.text} {marker}")

    print(f"\nExplanation: {question.explanation}")
    print(f"\nSource: {question.source_reference.document}")
    print(f"        Page {question.source_reference.page}, {question.source_reference.section}")
    print("\n" + "=" * 70)


def main():
    print("=== Question Validation Tool ===\n")

    repo = QuestionRepository()

    # List unvalidated questions
    unvalidated = list_unvalidated_questions(repo)

    if not unvalidated:
        return

    print(f"\nOptions:")
    print("  1. Review questions one by one")
    print("  2. Mark all as validated")
    print("  3. Exit")

    choice = input("\nYour choice (1-3): ").strip()

    if choice == "1":
        # Review each question
        for i, question in enumerate(unvalidated, 1):
            review_question(question)

            print(f"\nQuestion {i} of {len(unvalidated)}")
            print("Options:")
            print("  v - Mark as validated (good quality)")
            print("  s - Skip (review later)")
            print("  d - Delete (poor quality)")
            print("  q - Quit")

            action = input("\nAction (v/s/d/q): ").strip().lower()

            if action == 'v':
                question.validated = True
                repo.create(question)  # Update in database
                print("✅ Marked as validated")

            elif action == 'd':
                confirm = input("⚠️  Delete this question? (yes/no): ")
                if confirm.lower() == 'yes':
                    from repositories.base_repository import BaseRepository
                    base_repo = BaseRepository(repo.table_name)
                    base_repo.delete_item({'question_id': question.question_id})
                    print("🗑️  Deleted")
                else:
                    print("Cancelled")

            elif action == 'q':
                print("\nExiting...")
                break

            print()

    elif choice == "2":
        confirm = input(f"⚠️  Mark all {len(unvalidated)} questions as validated? (yes/no): ")
        if confirm.lower() == 'yes':
            for question in unvalidated:
                question.validated = True
                repo.create(question)
            print(f"✅ Marked {len(unvalidated)} questions as validated")
        else:
            print("Cancelled")

    print("\n✨ Done!")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Interrupted by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n\n❌ Error: {str(e)}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
